.npmrc
package-lock.json
package.json
src/graphql/directives/auth.js
src/security/jwt.js

* updates debug namespaces
* removes github packages references as now pushing to npm

fixes namespace and pulls from gh packages

---

package.json
src/graphql/directives/auth.js
src/graphql/directives/lowerCase.js
src/graphql/directives/upperCase.js
src/graphql/index.js

* adds lowerCase directive
* adds upperCase directive
* fixed undefined bug with a user not having permissions

adds new directives and fixes undefined bug

---

.vscode/settings.json
package-lock.json
package.json
src/graphql/directives/auth.js
src/security/jwt.js

* bumped packages to get new jwks client
* JWKS client now caches by default, taking their default values
* added an additional check to the user context of user is undefined. will now throw error that no user exists.

updates jwks pacakge, updated error handling on user context

---

package-lock.json
package.json
src/index.js
src/utility/firestoreDateForge.js
src/utility/index.js

Provides single reference functions to correct FireStore dates in the api's.

date forge for FireStore dates

---

src/graphql/directives/auth.js

I'm **not** going to push a new version to npm. whenever a real features goes up that can just ride along.

just added some deeper debugging

---

package-lock.json
package.json
src/dataSources/cloudFirestore/asset.js
src/dataSources/index.js
src/utility/firestoreDateForge.js

add asset datasource for entities. add dateForge for assets
fixes #32 
minor package bumps

shared asset queries

---

package-lock.json
package.json
src/dataSources/cloudFirestore/slug.js
src/envConfig.js
src/index.js
src/mentions/__tests__/mentions.test.js
src/mentions/index.js
src/mentions/parseToSlug.js
src/mentions/parseToToken.js

Closes #34 
Function for parsing mention tokens (`@slug`) from text (with tests).
function for looking up parsed tokens in slug table.

adding mention parsing functions and slug query

---

package.json
src/mentions/parseToSlug.js

closes #37 
part of thatconference/that-api-sessions#111

add option for mention matching case sensitivity

---

package-lock.json
package.json
src/dataSources/cloudFirestore/history.js

add history collection for THAT events. 
Minor package bumps

add history collection for THAT events

---

package-lock.json
package.json
src/constants.js
src/dataSources/cloudFirestore/event.js
src/dataSources/index.js
src/utility/__tests__/firestoreDateForge.test.js
src/utility/firestoreDateForge.js

Add event cloudDatastore
update constants
fix dateForge to use entityDateForge function
minor package bump

Add event cloudDatastore

---

package-lock.json
package.json
src/dataSources/cloudFirestore/memberExternal.js

return members from array of ID's
Audit fix for vulnerabilities

find members batch function added

---

package.json
src/utility/firestoreDateForge.js

v2.5.0
Non-breaking change, required for new event date object

Add ticket sale start and stop dates

---

package.json
src/dataSources/cloudFirestore/memberExternal.js

v2.6.0
copies shared function to THAT.api.

adds member get w/ typename

---

package.json
src/events/graphCdn/purgeEntityMutations.js

add AcceptedSession to session  purge

---

package-lock.json
package.json
src/orbitLove/activityTypes.js
src/orbitLove/orbitLoveApi.js

v2.8.1
Adds more detail for purchase and speaker activities sent to Orbit.Love

build out orbit purchase  and speaker activities

---

package.json
src/security/__tests__/requestSignature.test.js
src/security/index.js
src/security/requestSignature.js

v2.9.2
Forgot to expose function signingRequest, fixed.

new request signing function wasn't exposed so couldn't reference

---

package-lock.json
package.json
src/envConfig.js
src/events/graphCdn/index.js
src/lib/socialsBuffer.js
src/orbitLove/orbitLoveApi.js

v2.10.0
using library @adobe/node-fetch-retry
add wrapper to
- graphCdn calls
- orbit.love calls
- buffer calls
fixes #85 
fixes #82

Add node-fetch-retry wrapper to outbound requests

---

package.json
src/security/jwt.js

passing possible jwt key check error back through callback

---

package.json

correct for alpha version

---

package-lock.json
package.json
src/dataSources/cloudFirestore/history.js

v3.0.1
Fix issue incrementing firebase field by replacing firebase-admin with @google-cloud/firestore for reference to increment command.

Fix firestore increment field issue

---

package.json
src/events/graphCdn/index.js

v3.0.2
Fixes Sentry object validation
`Sentry.Severity` removed from Sentry

refactor Sentry object validation

---

package-lock.json
package.json
src/dataSources/cloudFirestore/product.js
src/dataSources/index.js

v3.2.0
Exports cloudFirstore/partner to api user
fix #94 , update Promise.all to db.getAll
minor package bumps.

Exposes partner store to api users

---

package.json
src/events/favorites.js
src/events/index.js

v3.4.1
Add favorites cache event emitter

adds favorites cache event emitter

---

package.json
src/events/favorites.js

v3.4.2
Fix bug in referenced method name

fix method typo

---

README.md
package.json
src/utility/__tests__/setValueAtPath.test.js
src/utility/setValueAtPath.js

v4.0.1
🤦 Left unsaved update locally for setValueAtPath fix
Update readme for v4

fix unsaved setValueAtPath update

---

package-lock.json
package.json
src/dataSources/cloudFirestore/memberExternal.js

v4.2.0
Adds new member functions: findMemberIdBySlug and findMemberBySlug.
minor package updates

feat: new function get member by slug
